# Generated by Django 2.2.1 on 2019-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0002_auto_20190525_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
