# Generated by Django 2.2.1 on 2019-05-28 17:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0003_auto_20190525_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='atelier_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
