# Generated by Django 2.2.1 on 2019-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0005_auto_20190802_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan_url',
        ),
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
