# Generated by Django 2.2.1 on 2019-09-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0006_auto_20190806_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atelier',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_title',
            new_name='title',
        ),
    ]
