# Generated by Django 2.2.1 on 2019-10-14 20:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0007_auto_20190909_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-order']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
