# Generated by Django 2.2.1 on 2019-10-27 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0008_auto_20191014_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['is_plan', 'order']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='is_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibit.Project'),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
